SELECT * FROM TIPO_EMPLEADO;

INSERT INTO TIPO_EMPLEADO (NOMBRE,DESCRIPCION) VALUES 
('SUPERVISOR',''),
('ADMINISTRADOR',''),
('ASEADOR','');

SELECT * FROM LOGIN;
SELECT * FROM PERSONA;
SELECT * FROM EMPLEADO;
INSERT INTO EMPLEADO (LOGIN_ID, PERSONA_ID, TIPO_EMPLEADO_ID) VALUES (1,1,1);

SELECT * FROM TIPO_LUGAR;
SELECT * FROM LUGAR;
INSERT INTO LUGAR (NOMBRE,DESCRIPCION,TIPO_LUGAR_ID) VALUES ('LUGAR-1','DESCRIPCION DE LUGAR-1',1);
SELECT * FROM SUPERVISION;

SELECT * FROM EVALUACION;
SELECT * FROM CALIFICACION_ACTIVIDAD;