SELECT * FROM TIPO_EMPLEADO;

INSERT INTO TIPO_EMPLEADO (NOMBRE,DESCRIPCION) VALUES 
('SUPERVISOR',''),
('ADMINISTRADOR',''),
('ASEADOR','');

SELECT * FROM LOGIN;
SELECT * FROM PERSONA;
SELECT * FROM EMPLEADO;
INSERT INTO EMPLEADO (LOGIN_ID, PERSONA_ID, TIPO_EMPLEADO_ID) VALUES (1,1,1);

SELECT * FROM TIPO_LUGAR;
SELECT * FROM LUGAR;
INSERT INTO LUGAR (NOMBRE,DESCRIPCION,TIPO_LUGAR_ID) VALUES ('LUGAR-1','DESCRIPCION DE LUGAR-1',1);
SELECT * FROM SUPERVISION;

SELECT * FROM EVALUACION;
SELECT * FROM ACTIVIDAD;
SELECT * FROM CALIFICACION_ACTIVIDAD;
INSERT INTO CALIFICACION_ACTIVIDAD (NOMBRE, ACTIVIDAD_ID) VALUES 
('COMPLETA',1), ('INCOMPLETA',1), ('FALTANTE',1);

INSERT INTO CALIFICACION_ACTIVIDAD (NOMBRE, ACTIVIDAD_ID) VALUES 
('COMPLETA',2), ('INCOMPLETA',2), ('FALTANTE',2);

SELECT * FROM ACTIVIDAD_TIPO_LUGAR;

UPDATE ACTIVIDAD_TIPO_LUGAR SET ACTIVIDAD_ID=2 WHERE ID=2;

SELECT * FROM EMPLEADO;
SELECT * FROM SUPERVISION;
INSERT INTO SUPERVISION (SUPERVISOR_ID, LUGAR_ID,FECHA)
VALUES (1,1,NOW());